inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - spec/spec_helper.rb
    - tmp/*
    - Gemfile
    - Guardfile
    - vendor/**/*
